name: lemmy_handshake
description: Mobile tool to synchronize multiple lemmy accounts across instances

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.0.0
  path: ^1.8.0
  intl: ^0.17.0  
  cupertino_icons: ^1.0.2
  sqflite_common_ffi: ^2.2.5
  http: ^0.13.5
  logger: ^1.0.0 
  flutter_secure_storage: ^4.2.1
  get_time_ago: ^1.1.8
  dynamic_color: ^1.5.4
  flutter_windows_vault: ^1.0.1
  workmanager: ^0.5.1
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  permission_handler: ^10.4.3
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  msix: ^3.16.1
flutter_icons:
  image_path: "assets/handshake_logo.png"
  android: true
  ios: true
flutter:
  uses-material-design: true

  assets:
    - assets/lemmy.png
